enabled: true

data_target: dataset
model_target: saved_model.dvc

data_remote: data_remote
models_remote: models_remote

pull_data_before_train: true
pull_model_before_infer: true
push_model_after_train: false
