[project]
name = "music-genre-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "IlyaYakovenko", email = "iakovenko.io@phystech.edu" }
]
requires-python = ">=3.11"
dependencies = [
    "antialiased-cnns>=0.3",
    "dvc>=3.67.1",
    "dvc-gdrive>=3.0.1",
    "fastai>=2.7.19",
    "fire>=0.7.1",
    "hydra-core>=1.3.3",
    "kagglehub>=1.0.2",
    "kornia>=0.8.3",
    "lightning>=2.6.5",
    "matplotlib>=3.9.4",
    "mlflow>=3.14.0",
    "numpy>=2.0.2",
    "omegaconf>=2.3.1",
    "onnx>=1.22.0",
    "onnxruntime>=1.27.0",
    "onnxscript>=0.7.0",
    "pandas>=2.3.3",
    "pillow>=11.3.0",
    "scikit-learn>=1.6.1",
    "soundfile>=0.14.0",
    "torchaudio>=2.11.0",
    "torchmetrics>=1.9.0",
]

[project.scripts]
music-genre-classifier = "music_genre_classifier.main:main"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "ruff>=0.15.18",
]
