checkpoint_path: saved_model/fold_0/checkpoints/best.ckpt
checkpoint_paths:
  - saved_model/fold_0/checkpoints/best.ckpt
  - saved_model/fold_1/checkpoints/best.ckpt

onnx_path: exported_model/music_genre_classifier_ensemble.onnx
triton_repository_dir: triton_model_repository
triton_model_name: music_genre_classifier

device: cpu
batch_size: 1
input_channels: 3
opset_version: 18

verify: true
verify_tolerance: 0.0001
pull_model_before_export: false

tensorrt_engine_path: exported_model/music_genre_classifier_ensemble.plan
tensorrt_precision: fp16
