max_epochs: 1
batch_size: 32
learning_rate: 0.002

label_smoothing: 0.15
mixup_alpha: 0.4
optimizer: adamw

accelerator: auto
devices: auto
precision: 16-mixed

resume: false
save_every_n_train_steps: 100
enable_progress_bar: true

output_dir: saved_model

scheduler: onecycle
onecycle_pct_start: 0.25
onecycle_div_factor: 25.0
onecycle_final_div_factor: 10000.0
